name: Test Workflow
on: [pull_request]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Run JUnit Tests
<<<<<<< HEAD
        run: ./gradlew test
=======
        run: ./gradlew test
>>>>>>> 609ba004621ab6cba97f13af6fa5d31f0dbcb91d
